// react/04_forms/src/components/ContactForm.tsx
import React,{useState} from 'react';
import Person from '../models/Person';

interface State {
	firstname:string;
	lastname:string;
}

interface Props {
	setGreeting(person:Person):void;
}

const ContactForm = (props:Props) => {
	
	const [state,setState] = useState<State>({
		firstname:"",
		lastname:""
	})
	
	const onChange = (event:React.ChangeEvent<HTMLInputElement>) => {
		setState((state) => {
			return {
				...state,
				[event.target.name]:event.target.value
			}
		})
	}
	
	const onSubmit = (event:React.SyntheticEvent) => {
		event.preventDefault();
		const person = new Person(state.firstname,state.lastname);
		props.setGreeting(person);
		setState({
			firstname:"",
			lastname:""
		})
	}
	return(
		<form onSubmit={onSubmit}>
			<label htmlFor="firstname">First Name</label>
			<input type="text"
					name="firstname"
					id="firstname"
					onChange={onChange}
					value={state.firstname}/>
			<br/>
			<label htmlFor="lastname">Last Name</label>
			<input type="text"
					name="lastname"
					id="lastname"
					onChange={onChange}
					value={state.lastname}/>
			<br/>
			<input type="submit" value="Greet"/>
		</form>
	)
}

export default ContactForm;

// angular/i_routing_one/src/app/components/contactform.component.ts
import {Component} from '@angular/core';
import {Contact} from '../models/contact.model';
import {FormsModule} from '@angular/forms';
import {ContactService} from '../services/contact.service';

@Component({
	selector:"contact-form",
	standalone:true,
	imports:[FormsModule],
	templateUrl:"./contactform.component.html"
})
export class ContactForm {
	
	contact = new Contact("","","","",0);
	
	constructor(private contactService:ContactService) {}
	
	addContact() {
		this.contactService.addContact(this.contact);
		this.contact = new Contact("","","","",0);
	}
}

<form (ngSubmit)="addContact()" #contactForm="ngForm">
	<label for="firstname">First name</label>
	<input type="text"
			name="firstname"
			id="firstname"
			[(ngModel)]="contact.firstname"/>
	<br/>
	<label for="lastname">Last name</label>
	<input type="text"
			name="lastname"
			id="lastname"
			[(ngModel)]="contact.lastname"/>
	<br/>
	<label for="email">Email</label>
	<input type="email"
			name="email"
			id="email"
			[(ngModel)]="contact.email"/>
	<br/>
	<label for="phone">Phone</label>
	<input type="tel"
			name="phone"
			id="phone"
			[(ngModel)]="contact.phone"/>
	<br/>
	<input type="submit" value="Add Contact"/>
</form>
